### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by adithep** [qvantel/jsonapi-scala#11]
Followed the example and got

Error:(10, 20) Cannot find JsonApiWriter or JsonApiFormat type class for ata.this.Company
  val json = rawOne(acme)****

Also there is no "rawOne" in spray.JsonApiSupport so I had to import by

import com.qvantel.jsonapi._

**Comment by bizm** [comment]
I'm getting the same " value readOne is not a member of object com.qvantel.jsonapi.spray.JsonApiSupport". This code is not working. Believe nobody checked it before publishing.

**Comment by Doikor** [comment]
Updated the example. It mostly broke due to bunch of code being moved around when we spilt the spray-http bits to its own sub project so we can have a scala 2.12 build.
